Client.create!([
  {name: "Amazon.com",
    address: "123 E ANYSTREET DR STE 150 ANYWHERE, CA 83616",
    worker: "Roy Batty",
    date: "2019-03-14",
    nature: "Business",
    business: "Amazon.com, PLLC (”Amazon”), a Delaware Corporation",
    work_type: "Sales",
    signatory: "Roy Batty",
    title: "CEO",
    notes: "1. *Company* will charge a monthly sprint fee of $60000.00.\r\n2. Payment is due at the beginning of each 30 day work period (Net 0).\r\n3. *Client* guarantees payment in full for the first 7 days of the agreement with no option for termination.\r\n4. Following the initial, guaranteed 7 day period, this retained service agreement may be terminated by either party for any reason and without cause. Written notice to *Company* is required to terminate the agreement.\r\n5. *Client* agrees to provide *Company* with administrative password access and network privileges sufficient to accomplish tasks.",
    services: "* Perform software and hardware integration .\r\n* Advise *Client* of software changes and security issues.\r\n* Develop technical specifications for hardware and software interaction.\r\n* Create physical test environments on standard hardware.\r\n* Develop interfaces with 3rd party block chain services such as U-Ledger.",
    payments: "1. The first payment of $60000 is due upon execution of the agreement.\r\n2. Subsequent payment of $6000 are due at the beginning of each new monthly sprint work period.\r\n3. This agreement may not be terminated during the first 7 days.\r\n4. Following the initial, guaranteed 7 day period, the agreement may be terminated for any reason and without cause. Written notice is required to terminate the agreement.\r\n5. Unpaid balances for goods and services bear interest from the due date at the rate of 1.5% per month until paid.",
    breach_period: "30",
    business_type: "hardware production of server monitoring equipment, services and technology related to solutions for e-commerce, and more broadly the affiliate and marketing industries, and any other application features or functionality related to the same",
    expense: "$25"},
  {name: "Apogee Designs",
    address: "123 AnyStreet",
    worker: "J.F. Sebastian",
    date: nil,
    nature: "Software Development",
    business: "Apogee Designs, LLC.",
    work_type: "Work For Hire",
    signatory: "J.F. Sebastian",
    title: "President",
    notes: "1. *Company* will charge a weekly sprint fee of $13500.00.\r\n2. Payment is due at the beginning of each 7 day work period (Net 0).\r\n3. *Client* guarantees payment in full for the first 7 days of the agreement with no option for termination.\r\n4. Following the initial, guaranteed 7 day period, this retained service agreement may be terminated by either party for any reason and without cause. Written notice to *Company* is required to terminate the agreement.\r\n5. *Client* agrees to provide *Company* with administrative password access and network privileges sufficient to accomplish tasks.",
    services: "* Perform Ruby on Rails application tuning and performance.\r\n* Advise *Client* of Ruby and/or Rails changes and security issues.\r\n* Examine and enhance performance within application and mobile app.",
    payments: "1. The first payment of $13500 is due upon execution of the agreement.\r\n2. Subsequent payment of $13500 are due at the beginning of each new weekly sprint work period.\r\n3. This agreement may not be terminated during the first 7 days.\r\n4. Following the initial, guaranteed 7 day period, the agreement may be terminated for any reason and without cause. Written notice is required to terminate the agreement.\r\n5. Unpaid balances for goods and services bear interest from the due date at the rate of 1.5% per month until paid.",
    breach_period: "3",
    business_type: "Design Services",
    expense: "$500"},
  {name: "Whole Foods",
    address: "123 AnyStreet",
    worker: "Rick Deckard",
    date: nil,
    nature: "Food Services",
    business: "Whole Foods, LLC.",
    work_type: "Work For Hire",
    signatory: "Rick Deckard",
    title: "President",
    notes: "1. *Company* will charge a monthly  fee of $35000.00.\r\n2. Payment is due at the beginning of each 7 day work period (Net 0).\r\n3. *Client* guarantees payment in full for the first 7 days of the agreement with no option for termination.\r\n4. Following the initial, guaranteed 7 day period, this retained service agreement may be terminated by either party for any reason and without cause. Written notice to *Company* is required to terminate the agreement.\r\n5. *Client* agrees to provide *Company* with administrative password access and network privileges sufficient to accomplish tasks.",
    services: "* Perform e-commerce evaluation and performance.\r\n* Advise *Client* of security issues.\r\n* Examine and enhance performance within web application and mobile app.",
    payments: "1. The first payment of $35000 is due upon execution of the agreement.\r\n2. Subsequent payment of $35000 are due at the beginning of each new weekly sprint work period.\r\n3. This agreement may not be terminated during the first 7 days.\r\n4. Following the initial, guaranteed 7 day period, the agreement may be terminated for any reason and without cause. Written notice is required to terminate the agreement.\r\n5. Unpaid balances for goods and services bear interest from the due date at the rate of 1.5% per month until paid.",
    breach_period: "3",
    business_type: "Design Services",
    expense: "$500"}
])
